/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import core.LSBImageEncoding;
import java.awt.Graphics2D;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;


public class ExtractImage extends javax.swing.JFrame {
    
    private JFileChooser imgSaver = new JFileChooser();
    private File decryFile;
    private JFileChooser decryChooser = new JFileChooser();
    private BufferedImage foundImage;
    private BufferedImage decryImage;
    private LSBImageEncoding lsbImageEncoding=new LSBImageEncoding();
    private int foundType = 0;
    private File directory = decryChooser.getCurrentDirectory();

    /**
     * Creates new form ExtractImage
     */
    public ExtractImage() {
        initComponents();
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener( new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {   
                setVisible(false);
                dispose();
                new DataExtractOption().setVisible(true);
            }
        });
        
        decryChooser.setFileFilter(new FileNameExtensionFilter("Images (jpg, png)", "jpg", "JPG", "jpeg", "JPEG", "png", "PNG"));
        decryChooser.setAcceptAllFileFilterUsed(false);
        this.foundImage=null;
        btDecry.setEnabled(false);
        btSave.setVisible(false);
        lbCPath.setVisible(false);
        lbResult.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbChooseImage = new javax.swing.JLabel();
        btImageChooser = new javax.swing.JButton();
        lbCPath = new javax.swing.JLabel();
        btDecry = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        lbResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Extract Image");

        lbChooseImage.setText("Choose cover Image :");

        btImageChooser.setText("Choose  image");
        btImageChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImageChooserActionPerformed(evt);
            }
        });

        lbCPath.setForeground(new java.awt.Color(140, 56, 104));
        lbCPath.setText("cImage :");

        btDecry.setText("Extract");
        btDecry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecryActionPerformed(evt);
            }
        });

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        lbResult.setForeground(new java.awt.Color(140, 56, 104));
        lbResult.setText("Result :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbChooseImage)
                                .addGap(50, 50, 50)
                                .addComponent(btImageChooser)
                                .addGap(55, 55, 55)
                                .addComponent(lbCPath, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btDecry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbChooseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImageChooser)
                    .addComponent(lbCPath, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDecry)
                    .addComponent(btSave))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDecryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecryActionPerformed
        // TODO add your handling code here:
        if (decryFile != null) {
            BufferedImage decryImage = readImg(decryFile);
            String name=decryFile.getName();                       
            foundType = lsbImageEncoding.getType(decryImage);
            if(foundType==2)
            {
                lbCPath.setText(name + ", size: "
                            + decryFile.length() / 1024 + " KB, Pixels(W x H) : "
                            + decryImage.getWidth() + " X  "
                            + decryImage.getHeight());
                foundImage = lsbImageEncoding.discoverImage(decryImage);      
            }
            if(foundImage!=null)
            {
                alert("An Image is found...");
                btDecry.setVisible(false);
                btSave.setVisible(true);
                lbResult.setVisible(true);
                lbResult.setText("Size: "
                            + decryFile.length() / 1024 + " KB, Pixels(W x H) : "
                            + foundImage.getWidth() + " X  "
                            + foundImage.getHeight());
                
            }
            else
            {
                alert("No image found... Incorrect file selected or data corrupted.");
            }
        }
    }//GEN-LAST:event_btDecryActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        export(foundImage, saveFile(imgSaver));
        reset(imgSaver);
        alert("Found Image saved Successfully....");
        setVisible(false);
        dispose();
        new Main(false).setVisible(true);
        
        
    }//GEN-LAST:event_btSaveActionPerformed

    private void btImageChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImageChooserActionPerformed
        // TODO add your handling code here:
        decryFile = openFile(decryChooser);
        if (decryFile != null) 
        {
            try{
                decryImage = ImageIO.read(decryFile);
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            
            lbCPath.setVisible(true);
            String name=decryFile.getName();
            lbCPath.setText(name + ", size: "
                            + decryFile.length() / 1024 + " KB, Pixels(W x H) : "
                            + decryImage.getWidth() + " X  "
                            + decryImage.getHeight());            
            btDecry.setEnabled(true);
        }
    }//GEN-LAST:event_btImageChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtractImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtractImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtractImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtractImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtractImage().setVisible(true);
            }
        });
    }
    
    
    /**
  * This method lets the user load a file from a directory using a JFileChooser.
  *
  * @param chooser the JFileChooser that is being used for the loading
     * @return 
  */
  public File openFile(JFileChooser chooser) {
        alert("Inside openFile method ");
        int dialog = chooser.showOpenDialog(this);
        if (dialog == JFileChooser.APPROVE_OPTION) {
        return chooser.getSelectedFile();
        } else if (dialog == JFileChooser.CANCEL_OPTION) {
            return chooser.getSelectedFile();
        } else {
            return new File("");
        }
  }
  
  
  /**
  * This method reads an image from a path and repaints it to an "argb"-type BufferedImage.
  *
  * @param inputFile the file to the image
  */
  public BufferedImage readImg(File inputFile) {
      alert("Inside readImg method...");
    BufferedImage img = null;
    try {
      BufferedImage bildIn = ImageIO.read(inputFile);
      img = new BufferedImage(bildIn.getWidth(), bildIn.getHeight(), BufferedImage.TYPE_INT_ARGB);
      Graphics2D g = img.createGraphics();
      g.drawImage(bildIn, 0, 0, null);
      g.dispose();
    } catch(IOException e) {
      System.out.println(e);
    }
    return img;
  }
  
  /**
  * This method lets the user pick a file in a directory using a JFileChooser for saving a file.
  *
  * @param chooser the JFileChooser that is being used
  */
  public File saveFile(JFileChooser chooser) {
      alert("Inside saveFile method...");
   int dialog = chooser.showSaveDialog(this);
   if (dialog == JFileChooser.APPROVE_OPTION) {
     return chooser.getSelectedFile();
   } else if (dialog == JFileChooser.CANCEL_OPTION) {
     return chooser.getSelectedFile();
   } else {
     return new File("");
   }
  }
  
  
  /**
  * This method exports a BufferedImage to an imagefile.
  *
  * @param img the BufferedImage that should be exported
  * @param outputFile the File in which the image should be saved
  */
  public void export(BufferedImage img, File outputFile) {
      alert("Inside export method...");
    try {
      ImageIO.write(img, "png", outputFile);
    } catch(IOException e){
      System.out.println(e);
    }
  }
  
  
  /**
  * This method resets the selected file and directory of a FileChooser.
  *
  * @param chooser the JFileChooser that will be resetted.
  */
  public void reset(JFileChooser chooser) {
      alert("Inside reset method...");
    chooser.setSelectedFile(new File(""));
    chooser.setCurrentDirectory(this.directory);
  }
  
  private static void alert(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDecry;
    private javax.swing.JButton btImageChooser;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel lbCPath;
    private javax.swing.JLabel lbChooseImage;
    private javax.swing.JLabel lbResult;
    // End of variables declaration//GEN-END:variables
}
