package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class Main extends javax.swing.JFrame
{   
    public Main(boolean usedTheApplication)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ThankYouDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ThankYouDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ThankYouDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ThankYouDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
 
        addWindowListener( new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                JFrame frame = (JFrame)e.getSource();
                Toolkit.getDefaultToolkit().beep();
                int result = JOptionPane.showConfirmDialog(frame, "Do you want to close the application?", "Exit Application", JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION)
                {
                    if(usedTheApplication)
                    {
                        new ThankYouDialog(new javax.swing.JFrame(),true).setVisible(rootPaneCheckingEnabled);
                    }
             
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                }
                    
            }
        });
        ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("BhuLogo.jpg")));
        Image img1=myimage.getImage();
        Image img2=img1.getScaledInstance(lblBhuLogo.getWidth(),lblBhuLogo.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(img2);
        lblBhuLogo.setIcon(i);
        this.encryptButton.setVisible(false);
        this.decryptButton.setVisible(false);
        this.cryptoGraphyButton.setEnabled(false);
        this.hideButton.setVisible(false);
        this.extractButton.setVisible(false);
        this.steganoGraphyButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBhuLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        decryptButton = new javax.swing.JButton();
        encryptButton = new javax.swing.JButton();
        lblAboutHeading = new javax.swing.JLabel();
        lblLine2 = new javax.swing.JLabel();
        lblLine1 = new javax.swing.JLabel();
        lblLine3 = new javax.swing.JLabel();
        lblLine4 = new javax.swing.JLabel();
        lblLine5 = new javax.swing.JLabel();
        lblLine6 = new javax.swing.JLabel();
        lblLine8 = new javax.swing.JLabel();
        lblLine7 = new javax.swing.JLabel();
        lblChoice = new javax.swing.JLabel();
        hideButton = new javax.swing.JButton();
        extractButton = new javax.swing.JButton();
        steganoGraphyButton = new javax.swing.JButton();
        cryptoGraphyButton = new javax.swing.JButton();
        chooseOptionButton = new javax.swing.JButton();
        lblOrangeLineBottom = new javax.swing.JLabel();
        lblBlueLineBottom = new javax.swing.JLabel();
        lblBlueLineTop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRIVACY MANAGER (AKM-17419MCA001)");
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setAlignmentY(0.0F);

        lblTitle.setBackground(new java.awt.Color(255, 102, 0));
        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PRIVACY MANAGER APPLICATION");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setOpaque(true);

        lblName.setBackground(new java.awt.Color(0, 204, 0));
        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Designed by ABHINAY KUMAR MISHRA. Copyright © 2020-2021. All rights are reserved.");
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblName.setOpaque(true);

        lblBhuLogo.setBackground(new java.awt.Color(255, 255, 0));
        lblBhuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/BhuLogo.jpg"))); // NOI18N
        lblBhuLogo.setOpaque(true);

        decryptButton.setBackground(new java.awt.Color(0, 204, 0));
        decryptButton.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        decryptButton.setText("FILE DECRYPTER");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        encryptButton.setBackground(new java.awt.Color(255, 255, 255));
        encryptButton.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        encryptButton.setText("FILE ENCRYPTER");
        encryptButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });

        lblAboutHeading.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblAboutHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAboutHeading.setText("ABOUT APPLICATION");
        lblAboutHeading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblLine2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLine2.setText("software can be used to provide and maintain the privacy and security of data of user from un- ");

        lblLine1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLine1.setText("\"PRIVACY MANAGER\" application is a standalone system based on Java platform. This application");

        lblLine3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLine3.setText("-authorized and unauthenticated access. This privacy manager software helps users to prevent");

        lblLine4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLine4.setText("their data from getting misused by others. This application uses two very popular mechanism to ");

        lblLine5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine5.setText("fulfil its objective- Cryptography and Steganography. Cryptography is art of secure writing where");

        lblLine6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLine6.setText("as steganography is art and science of hidden writing. We can use this software on various types");

        lblLine8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine8.setText("-mbination of these file types. This application software provides an easy user interface to users.");

        lblLine7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine7.setText("of multimedia file such as text file, image file, audio file, video file, interactive file type as well as co-");

        lblChoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChoice.setText("Please select one of the options to proceed further :");

        hideButton.setBackground(new java.awt.Color(255, 255, 255));
        hideButton.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        hideButton.setLabel("DATA HIDER");
        hideButton.setName(""); // NOI18N
        hideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonActionPerformed(evt);
            }
        });

        extractButton.setBackground(new java.awt.Color(255, 102, 0));
        extractButton.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        extractButton.setText("DATA EXTRACTER");
        extractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractButtonActionPerformed(evt);
            }
        });

        steganoGraphyButton.setBackground(new java.awt.Color(0, 204, 0));
        steganoGraphyButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        steganoGraphyButton.setText("STEGANOGRAPHY");
        steganoGraphyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steganoGraphyButtonActionPerformed(evt);
            }
        });

        cryptoGraphyButton.setBackground(new java.awt.Color(255, 102, 0));
        cryptoGraphyButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        cryptoGraphyButton.setText("CRYPTOGRAPHY");
        cryptoGraphyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cryptoGraphyButtonActionPerformed(evt);
            }
        });

        chooseOptionButton.setBackground(new java.awt.Color(0, 0, 255));
        chooseOptionButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        chooseOptionButton.setText("CHOOSE");
        chooseOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseOptionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAboutHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLine5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLine4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLine3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLine1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addComponent(lblLine6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLine8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cryptoGraphyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(steganoGraphyButton)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(encryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(decryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(extractButton, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(chooseOptionButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblLine7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAboutHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLine1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLine2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLine3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLine4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLine5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLine6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLine7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLine8)
                .addGap(26, 26, 26)
                .addComponent(lblChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseOptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(steganoGraphyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cryptoGraphyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(decryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extractButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        steganoGraphyButton.getAccessibleContext().setAccessibleDescription("");

        lblOrangeLineBottom.setBackground(new java.awt.Color(255, 102, 0));
        lblOrangeLineBottom.setOpaque(true);

        lblBlueLineBottom.setBackground(new java.awt.Color(0, 0, 255));
        lblBlueLineBottom.setMaximumSize(new java.awt.Dimension(34, 2));
        lblBlueLineBottom.setMinimumSize(new java.awt.Dimension(34, 2));
        lblBlueLineBottom.setOpaque(true);

        lblBlueLineTop.setBackground(new java.awt.Color(0, 0, 255));
        lblBlueLineTop.setMaximumSize(new java.awt.Dimension(34, 2));
        lblBlueLineTop.setMinimumSize(new java.awt.Dimension(34, 2));
        lblBlueLineTop.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 204, 0));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBlueLineTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOrangeLineBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblBhuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 378, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBlueLineBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBlueLineTop, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBhuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOrangeLineBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBlueLineBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_encryptButtonActionPerformed
    {//GEN-HEADEREND:event_encryptButtonActionPerformed
        FileChooser fileChooser = new FileChooser("ENCRYPT");
        fileChooser.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_decryptButtonActionPerformed
    {//GEN-HEADEREND:event_decryptButtonActionPerformed
        FileChooser fileChooser = new FileChooser("DECRYPT");
        fileChooser.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_decryptButtonActionPerformed

    private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
        // TODO add your handling code here:
        SecureLogin sc= new SecureLogin();
        sc.setVisible(true);
        sc.setTitle("HIDE DATA LOGIN WINDOW");
        setVisible(false);
        dispose();
        
  
    }//GEN-LAST:event_hideButtonActionPerformed

    private void extractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractButtonActionPerformed
        // TODO add your handling code here:
        SecureLogin sc= new SecureLogin();
        sc.setVisible(true);
        sc.setTitle("EXTRACT DATA LOGIN WINDOW");
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_extractButtonActionPerformed

    private void chooseOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseOptionButtonActionPerformed
        // TODO add your handling code here:
        this.cryptoGraphyButton.setEnabled(true);
        this.encryptButton.setVisible(false);
        this.decryptButton.setVisible(false);
        this.steganoGraphyButton.setEnabled(true);
        this.hideButton.setVisible(false);
        this.extractButton.setVisible(false);
    }//GEN-LAST:event_chooseOptionButtonActionPerformed

    private void cryptoGraphyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cryptoGraphyButtonActionPerformed
        // TODO add your handling code here:
        this.steganoGraphyButton.setEnabled(false);
        this.encryptButton.setVisible(true);
        this.decryptButton.setVisible(true);
        this.hideButton.setVisible(false);
        this.extractButton.setVisible(false);
    }//GEN-LAST:event_cryptoGraphyButtonActionPerformed

    private void steganoGraphyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steganoGraphyButtonActionPerformed
        // TODO add your handling code here:
        this.cryptoGraphyButton.setEnabled(false);
        this.encryptButton.setVisible(false);
        this.decryptButton.setVisible(false);
        this.hideButton.setVisible(true);
        this.extractButton.setVisible(true);
        
        
    }//GEN-LAST:event_steganoGraphyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Main(false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseOptionButton;
    private javax.swing.JButton cryptoGraphyButton;
    private javax.swing.JButton decryptButton;
    private javax.swing.JButton encryptButton;
    private javax.swing.JButton extractButton;
    private javax.swing.JButton hideButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAboutHeading;
    private javax.swing.JLabel lblBhuLogo;
    private javax.swing.JLabel lblBlueLineBottom;
    private javax.swing.JLabel lblBlueLineTop;
    private javax.swing.JLabel lblChoice;
    private javax.swing.JLabel lblLine1;
    private javax.swing.JLabel lblLine2;
    private javax.swing.JLabel lblLine3;
    private javax.swing.JLabel lblLine4;
    private javax.swing.JLabel lblLine5;
    private javax.swing.JLabel lblLine6;
    private javax.swing.JLabel lblLine7;
    private javax.swing.JLabel lblLine8;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrangeLineBottom;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JButton steganoGraphyButton;
    // End of variables declaration//GEN-END:variables
}
